### ISSUE TITLE
Entrust Integration with Venafi

### ISSUE THREAD

**Issue by shaimona** [Venafi/terraform-provider-venafi#10]
We use Entrust integration with Venafi. To request Entrust certs we need to pass email, full name and phone number. Is it possible to add those properties?

**Comment by tr1ck3r** [comment]
Hi @shaimona, to some degree that would go against what we have tried to accomplish with VCert.  Our objective was to rely on policy everywhere we could to minimize the data required by the invoker of VCert.  The contact related items you mentioned can all be set by policy using WebAdmin (Settings > Certificate Authorities) so that is the approach we recommend.  You will also need to use Trust Protection Platform 18.2 or higher because that is where the CA driver behavior was updated to use the smallest validity period defined by the CA template when none is selected for the certificate itself.
