### ISSUE TITLE
Enforcement of custom fields failing certificate creation 

### ISSUE THREAD

**Issue by jamestylerwarren** [Venafi/terraform-provider-venafi#11]
I'm receiving the following error when creating a certificate:

`Status: 400 Custom Field error. The value for the mandatory Custom Field Previous Expiration Date is not set.. Body: {"Error":"Custom Field error. The value for the mandatory Custom Field Previous Expiration Date is not set."}: {"Error":"Custom Field error. The value for the mandatory Custom Field Previous Expiration Date is not set."}`

**Background**: my current Terraform configuration was working until a recent upgrade to Venafi. Found this in the [19.3 release notes](https://support.venafi.com/hc/en-us/articles/360033418032-Important-Considerations-Before-Upgrading-to-TPP-19-3), although no solution was given:

> API/DevOps Integrations: Custom Fields for Certificates/Request
Update the POST Certificates/Request method to allow callers to specify Custom Field values at the same time as they request a certificate. Upgrade issue due to starting to enforce required Custom Fields.)

Has anyone encountered this issue? Solution? This seems like a configuration issue with Venafi itself and not the TF provider, just curious if anyone had seen this before....Thanks!!

**Comment by tr1ck3r** [comment]
Hi @jamestylerwarren, yes, this is the expected behavior in the current provider as it has not yet been enhanced to allow passing of Custom Fields.  In Trust Protection Platform 19.3 the `POST Certificates/Request` method started accepting and enforcing Custom Fields.  

https://support.venafi.com/hc/en-us/articles/360033779491

So at this time the answer is to make all certificate Custom Fields optional in the Trust Protection Platform configuration.  We do eventually want to update our Terraform provider to support Custom Fields but the timeline for that is unclear assuming delivery by Venafi Engineering.  If you haven't done so already, I would encourage you to submit an idea to https://ideas.venafi.com.  I can think of a couple ways that TPP could be enhanced to better handle this situation... one would be to have separate controls for required in the UI and required by the API.  Another would be to allow Custom Fields to be applied by policy (folder) rather than globally but this would only help here if you didn't want the required Custom Field value to apply to any Terraform requested certificates.

**Comment by jamestylerwarren** [comment]
Got it. Thanks for your help!
