### ISSUE TITLE
The certificates are emitted to stdout and no properly obfuscated

### ISSUE THREAD

**Issue by justinmchase** [Venafi/terraform-provider-venafi#131]
**PROBLEM SUMMARY**
When my certificate is updated, the old certificate is emitted to stdout of my CI logs and appears not to be treated as sensitive.

![Screenshot 2024-05-07 at 3 51 28 PM](https://github.com/Venafi/terraform-provider-venafi/assets/10974/1c81afaa-be54-44c2-9ef9-d90fcd9b2d65)

**STEPS TO REPRODUCE**
```tf
resource "time_rotating" "monthly" {
  rotation_minutes = 1
}

resource "random_password" "certificate_password" {
  length      = 12
  upper       = true
  lower       = true
  numeric     = true
  special     = false
  min_numeric = 1
  min_lower   = 1
  min_upper   = 1

  keepers = {
    time = time_rotating.monthly.id
  }
}

resource "venafi_certificate" "cert" {
  algorithm         = "RSA"
  custom_fields     = {}
  ecdsa_curve       = "P521"
  expiration_window = 72
  rsa_bits          = 2048
  valid_days        = 365
  common_name       = "example"
  san_dns           = "example.com"
  key_password      = random_password.certificate_password.result
}
```

1. Apply the template twice, 1 minute or more apart.

**EXPECTED RESULTS**
The secret values of the previous fields is obfuscated.

**ACTUAL RESULTS**
The entire certificate in its various forms is emitted to stdout.

**ENVIRONMENT DETAILS**
N/A

**COMMENTS/WORKAROUNDS**

**Comment by justinmchase** [comment]
Bueller? 

This is an important security issue.

**Comment by bonjoski** [comment]
Thank you for bringing this issue to our attention. This definitely looks like a security issue. We are working on reproducing the issue and will follow that up with a fix as appropriate.

**Comment by JigarAtVenafi** [comment]
Hi @justinmchase  Thank you for raising the issue.

The output you're seeing in the CI logs is the public portion of the certificate, which isn't considered sensitive. This information can be accessed via a TLS handshake or directly through a browser. This is by design, ensuring there's no security risk or bug involved.
 
Rest assured, all sensitive components—like the private key and password—are protected (not printed or written in plain-text) and are never exposed in logs or output.

Let us know if we have any question

**Comment by justinmchase** [comment]
The chain is but are you sure the certificate field is?

**Comment by JigarAtVenafi** [comment]
The public part of an SSL certificate, including the certificate chain and certificate fields, is indeed public by design. This information can be retrieved by anyone performing a TLS handshake with the server or by using tools like OpenSSL.
For example, you can use the following OpenSSL command to retrieve the certificate information from a popular website like [google.com](http://google.com/):

bash
openssl s_client -connect google.com:443 -showcerts
This command initiates a TLS handshake with Google's server and outputs the certificate chain, including the public certificate fields. Here’s a snippet of what the output might look like:
bash
Certificate chain
 0 s:/CN=*.
google.com/O=Google LLC/L=Mountain View/ST=California/C=US
   i:/C=US/O=Google Trust Services LLC/CN=GTS CA 1O1
-----BEGIN CERTIFICATE-----
MIIBijCCASGgAwIBAgIRAO1uItHb5MP8A5IdzJgfq/cwCgYIKoZIzj0EAwIwRjEL
...
-----END CERTIFICATE-----

As you can see, this includes details like the Common Name (CN) and the certificate issuer, which are public information.

**Comment by justinmchase** [comment]
Doesn't the `pkcs12` field contain a private key in it? Its totally printing out in plain text.

Honestly, I want 0 properties coming out of this even public keys printing out in plain text. I want all of these cert values as being sensitive, even almost 2 years later and it freaks me out every time I see it.
