### ISSUE TITLE
Venafi Provider Timeout Causing Intermitent Issues

### ISSUE THREAD

**Issue by smeluski** [Venafi/terraform-provider-venafi#16]
I am seeing the following error when running terraform plan: Error: Post https://***.corp.com/vedsdk/authorize/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  on certificate.tf line 1, in provider "venafi":
   1: provider venafi {

This happens intermittently. is it possible to increase the timeout or making it configurable?

**Comment by tr1ck3r** [comment]
@smeluski we're planning to transition our Terraform provider from API key (username/password) to token in Q3 so that should give us an opportunity to reassess whether our timeout is appropriate.  A couple questions that will help us with that... What is the average ping latency between your Terraform client and your Venafi WebSDK server?  How frequently do you restart your Venafi WebSDK (IIS) server?  Currently timeouts are expected if Terraform is the first client that hits the WebSDK server after it starts.

**Comment by tr1ck3r** [comment]
@smeluski any feedback on the questions I posed last week?  We also released a new version (v0.9.3) of our provider on Monday that increased one of the timeouts so I'm interested in hearing whether that eliminates the intermittent issues you are seeing?

**Comment by smeluski** [comment]
@tr1ck3r thanks for getting back to me so promptly and following up. I tested this several times today and did not run into the issue which is positive. Not sure if the changes resolved the issue or not, but I'll be continuing to use this and will let you know if anything comes up.

As for your prior questions: average ping latency 28ms with a max of 43 and a min of 24. Unfortunately, I do not manage the venafi servers myself so I would need to follow up on the frequency of restarts.

Thanks again for the follow-up.

**Comment by smeluski** [comment]
@tr1ck3r - I am no longer seeing this issue. Appears to have been resolved or something network / server related on my side.

**Comment by tr1ck3r** [comment]
Thank you for confirming @smeluski and happy that the issue seems to have been resolved.
