### ISSUE TITLE
Post Renew one entry is added in an empty san_dns list

### ISSUE THREAD

**Issue by gani247** [Venafi/terraform-provider-venafi#41]
Getting below error post renew..

`venafi_certificate.cert: unable to retrieve: Unexpected status code on TPP Certificate Retrieval. Status: 500 Certificate \VED\Policy\web\External Single-Domain\web.venfai.com has encountered an error while processing, Status: Cannot have Subject Alternate Names as it is not enabled on the Certificate Authority object., Stage: 0.
`
And cert is going to ERROR state

Why it is adding an entry(DNS name) in san_dns... can't we have single-domain certs?

**Comment by tr1ck3r** [comment]
@gani247 since the Common Name has been deprecated for many years now (I think Google Chrome stopped supporting it in 2017), I believe we followed current standards in our implementation and always include the Common Name as a DNS SAN.  Most, if not all, public CAs follow the same behavior when they issue certificates, basically helping users to correct their mistake.  To resolve the error you encountered you simply need to enable the SAN option on your CA template in the Venafi Platform.
