### ISSUE TITLE
Create Venafi device 

### ISSUE THREAD

**Issue by jmcshane** [Venafi/terraform-provider-venafi#5]
**BUSINESS PROBLEM**
Create Venafi device and credential from Terraform

**PROPOSED SOLUTION**
```
resource "venafi_credential" "private_key_credential" {
...
}
resource "venafi_device" "device" {
...
}
```

Don't have a full idea of what fields this would require, but I wanted to get this out here for discussion.

**CURRENT ALTERNATIVES**
API calls after `venafi_resource` is provisioned.

**VENAFI EXPERIENCE**
Using Venafi onprem solution

**Comment by tr1ck3r** [comment]
Hi @jmcshane, can you elaborate a bit more on what the "venafi_device" you proposed would do?  Are you seeking for the Terraform caller to be able to communicate where the requested certificate will be hosted, how it can be validated over TLS, and/or which application stack it belongs to?

**Comment by jmcshane** [comment]
Hey @tr1ck3r, I'm working within Venafi TPP and there are further options after a certificate is provisioned. You can set up `Devices and Apps` as well as `Access Credentials`. These are available under the sdk API as:

`/Config/*` for device
`/Credentials/*` for access credentials

I would be interested to expand past the current resource which only uses the `/Certificates/*` API path.

**Comment by jmcshane** [comment]
Config is of course an extremely broad API category and would need to be categorized under different configuration types available within Venafi

**Comment by tr1ck3r** [comment]
That goes in somewhat of a different direction than we've seen most Venafi customers go with Terraform.  Rather than having TPP be responsible for provisioning certificates to infrastructure created by Terraform, it is Terraform that orchestrates everything having to do with the workload including certificate acquisition (using the Venafi provider) and the subsequent installation of the certificate on the workload.  Generally the certificate outlives the workload but we have included expiration-based renewal intelligence in our provider so it could be used for longer-lived infrastructure.  Those cases are typically the ones where having TPP be responsible for renewing and provisioning certificates may make sense.  That said, we're not currently planning anything in that area for Terraform because our focus with it has been on the shorter-lived, continuously deployed infrastructure.

**Comment by jmcshane** [comment]
Makes sense, once you get the cert out of the API, then you can pass that cert anywhere using TF. I'll close the issue and think back through this workflow
