### ISSUE TITLE
Call to function "file" failed: contents of "./file/cabundle.pem" are not valid UTF-8

### ISSUE THREAD

**Issue by muralikrishnarokkam** [Venafi/terraform-provider-venafi#97]
Having an issue using terraform venafi, In that trust_bundle unable to use file function in terraform got an below error.

Call to function "file" failed: contents of "./file/cabundle.pem" are not valid UTF-8

**Comment by EduardoVV** [comment]
Hi @muralikrishnarokkam , thanks for raising this issue.

**Can you provide more information?**
- terraform version
- terraform-provider-venafi plugin version

**Can you also verifiy using `openssl` command to see if the PEM bundle contains any errors?**
`openssl verify -verbose ./file/cabundle.pem`

**And lastly, are you by any chance using a binary encoded PEM bundle instead of ascii armor?**

**Comment by luispresuelVenafi** [comment]
Hi there @muralikrishnarokkam ,

Did what @EduardoVV comment solved your issue?

**Comment by luispresuelVenafi** [comment]
I'm closing this issue so developers can focus on other work. We can re-open it if needed
